version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: postgres20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
      POSTGRES_DB: job_application_db
    ports:
      - "5121:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  backend:
    build:
      context: ./Backend
    container_name: backend24
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
      POSTGRES_DB: job_application_db
    ports:
      - "3213:3213"
    depends_on:
      - postgres
    restart: always

  employee_formfilling:
    build:
      context: ./Employee_Formfilling
    container_name: employee_formfilling25
    ports:
      - "6511:80"
    depends_on:
      - backend
    restart: always

  hr_formfilling:
    build:
      context: ./HR_FormFilling
    container_name: hr_formfilling26
    ports:
      - "6512:80"
    depends_on:
      - backend
    restart: always

  welcome_page:
    build:
      context: ./Welcome-Page
    container_name: welcome_page27
    ports:
      - "6513:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:

